### ISSUE TITLE
Ruby Constants not readable

### ISSUE THREAD

**Issue by mariojackson** [connorwyatt/sakura-intellij-theme#16]
Hey there,

I've been using your theme on multiple JetBrains IDEs and have generally found it to be impressive. However, I encountered an issue regarding the readability of constants in RubyMine with the Sakura Day theme. The color contrast appears too bright, making it challenging to read, likely because some attributes do not inherit the overall Ruby theme settings. In my example, it was the attribute for `Constants` in Ruby.

To resolve this, I enabled the 'Inherit from Global...' option, effectively addressing the problem. While navigating through this process, I noticed that other attributes, such as Symbols, do not have the 'Inherit from Global...' option enabled. This was not immediately apparent to me since I'm still familiarizing myself with the nuances of this new theme.

In the interim, I've manually adjusted the theme settings to 'Inherit from Global...' for these attributes. Still, you may want to consider enabling this setting by default to improve the user experience.

Thank you for creating this theme!

**Comment by connorwyatt** [comment]
Hi @mariojackson, sorry for the delay getting back to you on this!

I don't actually use Ruby so I've not tested it there, but will look into this for you and will get a fix out 👍 

Thanks for the feedback also and glad you like the theme 👍

**Comment by connorwyatt** [comment]
I've just rolled out a fix for this, it will be in `v0.19.0` but it will take a few days for JetBrains to verify the new version. Once the release is available on GitHub I'll link to it in this thread (should be about 10 mins).

**Comment by connorwyatt** [comment]
@mariojackson https://github.com/connorwyatt/sakura-intellij-theme/releases/tag/v0.19.0 if you want it early, this is the fixed version.

I'll close this for now, but let me know if you have any issues with it 👍

**Comment by connorwyatt** [comment]
It is now live in the JetBrains marketplace so the update should be showing in your IDE now 👍
