### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by minhquana3** [connorwyatt/sakura-intellij-theme#35]
First of all, thank you for this great theme. I'm really fond of it. 

I have two suggestions.
1. The color of the top bar is light aqua. To make the color theme consistent, I think the color of the top bar should be the primary color. 
![image](https://github.com/connorwyatt/sakura-intellij-theme/assets/90219512/e3460ded-41f6-4d4f-b098-0969d5865834)
2. I think it would be better if the color of two sidebars are the same as the primary background color. 
![image](https://github.com/connorwyatt/sakura-intellij-theme/assets/90219512/2cde9912-eb91-4131-ba6b-b41990febbeb)

**Comment by connorwyatt** [comment]
Hey @minhquana3, thanks for the feedback and sorry for the delay in getting back to you. The light cyan is some testing colors that I left in so I could identify where different colors are used as the documentation isn't the greatest. I will fix that and will take a look at your other suggestion 👍

**Comment by connorwyatt** [comment]
Hi @minhquana3 I've put a fix up for the cyan window title, so you should see that in a couple of days once JetBrains approve it. Regarding the sidebars, I quite like them how they are, but thank you for the suggestion
