### ISSUE TITLE
Increase visiblity of checkbox

### ISSUE THREAD

**Issue by Manapia** [connorwyatt/sakura-intellij-theme#37]
Thank you for developing the Sakura Night theme. Its design, inspired by sakura trees, is both beautiful and calming. As a Japanese user, I find it especially appealing and well-crafted.

I am writing this with the help of GPT, as I am not a native English speaker.

I’ve encountered an issue regarding checkbox visibility.

![settings dialog](https://github.com/user-attachments/assets/9453722b-7c9b-44e6-9852-4c02164012f6)

The background color of checkboxes appears the same whether they are checked or unchecked, making it difficult to distinguish their state.
This may be a bug, but the published screenshots don't show the checkbox, so I couldn't be sure this is correct.

The contrast between the checkmark and the background is relatively low, which makes it harder to notice at a glance.
While this may be an intentional design choice, I think improving the contrast or adjusting the background color for checked checkboxes would make the theme even more user-friendly.

I tried with IntelliJ IDEA 2024.3 (Ultimate Edition) #IU-243.21565.193

I will be glad to provide any information that is needed.

Thank you again for your excellent work. I hope you’ll consider this suggestion for a future update.

**Comment by connorwyatt** [comment]
Hi @Manapia, thanks for the kind words! I will of course look into this in the next couple of days for you 👍

**Comment by connorwyatt** [comment]
Hi @Manapia, I've uploaded an update to the JetBrains marketplace which should be usable in the next couple of days. They've been fairly quick recently.

Regarding the fix, I couldn't find much I could do with it unfortunately. It seems like JetBrains have a bug where in themes marked as dark mode themes, the background of the checkbox is always the selected color, whereas on light themes it's transparent. Marking the theme as a light mode theme would have other implications so it doesn't seem like a good idea.

Hopefully this helps with the visibility at least.

Let me know how you get on with it, I'll close this in the meantime 👍 

Thanks again for raising this issue

**Comment by Manapia** [comment]
Thank you for investigating this. It’s strange how the behavior changes depending on the theme type.

In my environment, the updated version of the theme is rendered like this:

![image1](https://github.com/user-attachments/assets/00b4d9ed-7341-4af3-95b9-2843f5d96232)
![image2](https://github.com/user-attachments/assets/596a97de-06d6-481b-a6c5-5fcc834acb7b)

It does seem that the visibility has improved. It’s much easier to see now!

I’ve been using this theme for a few days and have decided to switch to it. I’m also starting to get used to the unchecked checkboxes no longer having a transparent background. Thank you for sharing this theme with us :sparkles:

**Comment by connorwyatt** [comment]
Thank you for the feedback, and glad that it has helped. Looking at some other themes, they tend to keep the checkbox background transparent, which I could change it to if needed

**Comment by Manapia** [comment]
You're right—many other themes tend to use transparent checkboxes, which might make it easier for users migrating from other themes to feel more familiar.

To preserve the uniqueness of this theme, I think using a lighter shade of pink could also work well

<details>

![image](https://github.com/user-attachments/assets/a5da4db5-6a0e-4078-ba3e-38f83138c9ad)
</details>

That said, I’m not familiar with JetBrains IDE theme settings. If making the checkboxes transparent or using lighter colors unintentionally affects the background of other controls, it might be better to leave things as they are. The background color of the "OK" button, for example, doesn't seem to have changed (though it looks a bit too bright), so my concern may be unnecessary.

In any case, I’m happy with the current design. Thank you!
