### ISSUE TITLE
Low visibility text color in PHP code

### ISSUE THREAD

**Issue by Manapia** [connorwyatt/sakura-intellij-theme#38]
I found a low visibility text color in the PHP code.

![image](https://github.com/user-attachments/assets/5ed48fe4-d7d6-4599-9c2d-fab5cd6d762c)

This is found in Identifiers > Magic Member Access.

The color is probably not set because #0000FF is applied.

This screenshot is from IntelliJ IDEA 2024.3 (Ultimate Edition) #IU-243.21565.193.

Please let us know if you need any other information. I will provide it.

I found this theme from the list of recently updated plugins. I hope to make more improvements in the future.

**Comment by connorwyatt** [comment]
Hi @Manapia, thanks for raising this. It's very hard to work out what variable controls which thing in the UI so I put strong colours in place to make them stand out so I could find them. I will get this fixed in the next couple of days 👍

**Comment by connorwyatt** [comment]
Hi @Manapia, this is included in the next version (which should be available in the next couple of days).

I've set it to the color that is used for constants as I'm not familiar with what a magic member is. If you think it needs to be visually distinct from constants, I can look into that, but wanted to get something out that makes it usable.

**Comment by connorwyatt** [comment]
@Manapia FYI if you want access to it early, I create releases on here with the new version of the theme: https://github.com/connorwyatt/sakura-intellij-theme/releases/tag/v0.26.0

This release includes a fix for #37 as well

**Comment by Manapia** [comment]
@connorwyatt Thank you for the prompt response and fix.

I'm sorry for not explaining the about the "magic members". In PHP frameworks like Laravel and CakePHP, it's common to use PHPDoc comments to declare properties corresponding to database columns. This allows language servers and linters to recognize them, even though they aren't explicitly declared in the code.

For example:

```php
/**
 * @property string $name
 * @property int $age
 */
class Users extends Model {
}
```

In PHP, it's possible to access class members that haven't been pre-defined. For instance, in the following example, accessing an undeclared field (undefined) triggers the __get() method, which then returns a value:

```php
/**
 * @property string $undefined
 */
class Example {
  public function __get($name) {
    return 'Hello ' . $name;
  }
  
  public string $declared = '';
}

$instance = new Example();
print($instance->undefined);
print($instance->declared);

// Output: "Hello undefined"
```

In this context, $instance->undefined is highlighted as a "magic member."

After testing the new version, I noticed that this kind of code is now highlighted beautifully:

![image](https://github.com/user-attachments/assets/57a75aa9-2108-4151-b9fb-23037e02aa59)

It looks great now! Thank you for your support and quick response.

**Comment by connorwyatt** [comment]
@Manapia Brilliant to hear, thanks for the feedback! Glad you like the theme 👍
